development:
  adapter: postgresql
  database: railskating_development
  username: <%= ENV['RAILSKATING_USER'] %>
  password: <%= ENV['RAILSKATING_PASS'] %>

test: &test
  adapter: postgresql
  database: railskating_test
  username: <%= ENV['TRAVIS'] ? 'postgres' : ENV['RAILSKATING_USER'] %>
  password: <%= ENV['TRAVIS'] ? '' : ENV['RAILSKATING_PASS'] %>

production:
  adapter: postgresql
  database: railskating_production
  username: <%= ENV['RAILSKATING_USER'] %>
  password: <%= ENV['RAILSKATING_PASS'] %>

cucumber:
  <<: *test
