sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  username: <%= ENV['TRAVIS'] ? 'root' : ENV['RAILSKATING_USER'] %>
  password: <%= ENV['TRAVIS'] ? '' : ENV['RAILSKATING_PASS'] %>
  database: railskating_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  username: <%= ENV['TRAVIS'] ? 'postgres' : ENV['RAILSKATING_USER'] %>
  password: <%= ENV['TRAVIS'] ? '' : ENV['RAILSKATING_PASS'] %>
  database: railskating_<%= Rails.env %>

development:
  adapter: sqlite3
  database: db/development.sqlite3

test: &test
  adapter: sqlite3
  database: db/test.sqlite3

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "sqlite" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

cucumber:
  <<: *test
