require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdjudicatorsController do

  # This should return the minimal set of attributes required to create a valid
  # Adjudicator. As you add validations to Adjudicator, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all adjudicators as @adjudicators" do
      adjudicator = Adjudicator.create! valid_attributes
      get :index
      assigns(:adjudicators).should eq([adjudicator])
    end
  end

  describe "GET show" do
    it "assigns the requested adjudicator as @adjudicator" do
      adjudicator = Adjudicator.create! valid_attributes
      get :show, :id => adjudicator.id.to_s
      assigns(:adjudicator).should eq(adjudicator)
    end
  end

  describe "GET new" do
    it "assigns a new adjudicator as @adjudicator" do
      get :new
      assigns(:adjudicator).should be_a_new(Adjudicator)
    end
  end

  describe "GET edit" do
    it "assigns the requested adjudicator as @adjudicator" do
      adjudicator = Adjudicator.create! valid_attributes
      get :edit, :id => adjudicator.id.to_s
      assigns(:adjudicator).should eq(adjudicator)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Adjudicator" do
        expect {
          post :create, :adjudicator => valid_attributes
        }.to change(Adjudicator, :count).by(1)
      end

      it "assigns a newly created adjudicator as @adjudicator" do
        post :create, :adjudicator => valid_attributes
        assigns(:adjudicator).should be_a(Adjudicator)
        assigns(:adjudicator).should be_persisted
      end

      it "redirects to the created adjudicator" do
        post :create, :adjudicator => valid_attributes
        response.should redirect_to(Adjudicator.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved adjudicator as @adjudicator" do
        # Trigger the behavior that occurs when invalid params are submitted
        Adjudicator.any_instance.stub(:save).and_return(false)
        post :create, :adjudicator => {}
        assigns(:adjudicator).should be_a_new(Adjudicator)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Adjudicator.any_instance.stub(:save).and_return(false)
        post :create, :adjudicator => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested adjudicator" do
        adjudicator = Adjudicator.create! valid_attributes
        # Assuming there are no other adjudicators in the database, this
        # specifies that the Adjudicator created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Adjudicator.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => adjudicator.id, :adjudicator => {'these' => 'params'}
      end

      it "assigns the requested adjudicator as @adjudicator" do
        adjudicator = Adjudicator.create! valid_attributes
        put :update, :id => adjudicator.id, :adjudicator => valid_attributes
        assigns(:adjudicator).should eq(adjudicator)
      end

      it "redirects to the adjudicator" do
        adjudicator = Adjudicator.create! valid_attributes
        put :update, :id => adjudicator.id, :adjudicator => valid_attributes
        response.should redirect_to(adjudicator)
      end
    end

    describe "with invalid params" do
      it "assigns the adjudicator as @adjudicator" do
        adjudicator = Adjudicator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Adjudicator.any_instance.stub(:save).and_return(false)
        put :update, :id => adjudicator.id.to_s, :adjudicator => {}
        assigns(:adjudicator).should eq(adjudicator)
      end

      it "re-renders the 'edit' template" do
        adjudicator = Adjudicator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Adjudicator.any_instance.stub(:save).and_return(false)
        put :update, :id => adjudicator.id.to_s, :adjudicator => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested adjudicator" do
      adjudicator = Adjudicator.create! valid_attributes
      expect {
        delete :destroy, :id => adjudicator.id.to_s
      }.to change(Adjudicator, :count).by(-1)
    end

    it "redirects to the adjudicators list" do
      adjudicator = Adjudicator.create! valid_attributes
      delete :destroy, :id => adjudicator.id.to_s
      response.should redirect_to(adjudicators_url)
    end
  end

end
