require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CouplesController do

  # This should return the minimal set of attributes required to create a valid
  # Couple. As you add validations to Couple, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all couples as @couples" do
      couple = Couple.create! valid_attributes
      get :index
      assigns(:couples).should eq([couple])
    end
  end

  describe "GET show" do
    it "assigns the requested couple as @couple" do
      couple = Couple.create! valid_attributes
      get :show, :id => couple.id.to_s
      assigns(:couple).should eq(couple)
    end
  end

  describe "GET new" do
    it "assigns a new couple as @couple" do
      get :new
      assigns(:couple).should be_a_new(Couple)
    end
  end

  describe "GET edit" do
    it "assigns the requested couple as @couple" do
      couple = Couple.create! valid_attributes
      get :edit, :id => couple.id.to_s
      assigns(:couple).should eq(couple)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Couple" do
        expect {
          post :create, :couple => valid_attributes
        }.to change(Couple, :count).by(1)
      end

      it "assigns a newly created couple as @couple" do
        post :create, :couple => valid_attributes
        assigns(:couple).should be_a(Couple)
        assigns(:couple).should be_persisted
      end

      it "redirects to the created couple" do
        post :create, :couple => valid_attributes
        response.should redirect_to(Couple.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved couple as @couple" do
        # Trigger the behavior that occurs when invalid params are submitted
        Couple.any_instance.stub(:save).and_return(false)
        post :create, :couple => {}
        assigns(:couple).should be_a_new(Couple)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Couple.any_instance.stub(:save).and_return(false)
        post :create, :couple => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested couple" do
        couple = Couple.create! valid_attributes
        # Assuming there are no other couples in the database, this
        # specifies that the Couple created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Couple.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => couple.id, :couple => {'these' => 'params'}
      end

      it "assigns the requested couple as @couple" do
        couple = Couple.create! valid_attributes
        put :update, :id => couple.id, :couple => valid_attributes
        assigns(:couple).should eq(couple)
      end

      it "redirects to the couple" do
        couple = Couple.create! valid_attributes
        put :update, :id => couple.id, :couple => valid_attributes
        response.should redirect_to(couple)
      end
    end

    describe "with invalid params" do
      it "assigns the couple as @couple" do
        couple = Couple.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Couple.any_instance.stub(:save).and_return(false)
        put :update, :id => couple.id.to_s, :couple => {}
        assigns(:couple).should eq(couple)
      end

      it "re-renders the 'edit' template" do
        couple = Couple.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Couple.any_instance.stub(:save).and_return(false)
        put :update, :id => couple.id.to_s, :couple => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested couple" do
      couple = Couple.create! valid_attributes
      expect {
        delete :destroy, :id => couple.id.to_s
      }.to change(Couple, :count).by(-1)
    end

    it "redirects to the couples list" do
      couple = Couple.create! valid_attributes
      delete :destroy, :id => couple.id.to_s
      response.should redirect_to(couples_url)
    end
  end

end
